import pytest

from risk_assessment.readi.analyzer import READIAnalyzer


@pytest.mark.skip("Only for simple testing")
def test_from_pile():
    # data = """Well, I can’t say that I’m surprised. With eco-<|start_of_sens|>(MedicalTerm)awareness<|end_of_sens|> decidedly “In” and celebrity roasts of Ruth Buzzi “Out,” it makes sense that America’s Actor, AKA Jon Hamm, would attend the celebration of the National Resources Defense Council’s 20th anniversary this week. The fest included some of the most powerful and influential eco-celebs around, including Ed Begley Jr., Julia Louis-Dreyfus, and Steven Bochco. And Jon Hamm, with longtime girlfriend Jennifer Westfeldt, shared their secrets about how they conserve <|start_of_sens|>(MedicalTerm)energy<|end_of_sens|> to help save the planet.\nJon Hamm Enjoying Nature\nFrom the news report at Mother Nature Network: “There are a lot of options to take in your life and not be wasteful and selfish. If you put other people and the environment first instead of yourself, it’s a lot easier to make those decisions that decrease your impact on the environment.” Toward that end, Hamm and his girlfriend Jennifer Westfeldt watch their consumption. “We don’t use a lot of air-<|start_of_sens|>(MedicalTerm)conditioning<|end_of_sens|>. We open windows. We have a relatively small air-<|start_of_sens|>(MedicalTerm)conditioning<|end_of_sens|> bill, and we’re trying to get it smaller every day. The fact that we’re in California and there have been a lot of initiatives put forth to do that is great. We’re trying to take advantage of that as much as we can.”\nIf Jon Hamm isn’t channeling Steve Rogers here, then I don’t know what’s going on. Every person can do their part to put other people first, ahead of their own self-interest? What type of person says something that? Oh yeah, I forgot… every superhero in the universe! Somebody please get him in a meeting with Avi Arad! Cast him in “The First Avenger: Captain America” before he takes an indie gig to maintain his actor’s cred.\nWe all know he is not the first celebrity to back environmental issues, but when push comes to shove, it will be interesting to see where he comes down on laws concerning Green regulations."""

    examples = [
        "Men's MTB jersey SENTIERO\nMtb jersey with loose fit and fresh and comfortable fabrics for the summer. In addition to the high UPF protection, the fabric has Sanitized® anti-mite, antibacterial and permanent antifungal treatment. Functional jersey for mountain biking thanks to the front zip and rear zip pocket.\nPayments on the PayPal circuit can be made through a PayPal account or by credit card.\nWire transfer\nIf you have placed your order online, you will automatically receive the order confirmation by email, where you will find our bank details and the amount to be paid. The order will be shipped as soon as the payment is credited to our account.\nOur coordinates are:\nCREDIT AGRICOLE ITALIA SPA\nBank branch in Treviso (TV)\nABI 06230 CAB 12000\nC/C 000015030221\nSWIFT CODE\nCRPPIT2PXXX\nIBAN IT76R 06230 12000 000015030221\nCash on delivery\nOrders with cash on delivery are accepted only in Italy. You can pay in cash or by check. The cost of this service is Euro 5.\nThe shipment is made by TNT courier in case of destination in Italy, by FEDEX / DHL in case of destination outside the Italian territory.\nYou will receive emails that will promptly update you on the status of your shipment.\nShipping methods\nFor Italy, shipping is free for orders over € 80, if less, shipping costs € 7. The cash on delivery payment service costs € 5.The delivery of the shipment in the Italian territory is normally carried out in 24/48 hours.\nFor Europe, the minimum order amount must be € 100, below which shipping costs € 12. The delivery of the shipment outside the Italian territory is normally carried out from 2 to 4 working days depending on the destination. For express shipments the cost is € 17.",
        'Tena Rebernjak\nBring yoga into your home, practice online!\nI strive to shed light on, translate and de-mystify what yoga and meditation are, and bring it closer to everyone to get the most out of these practices. I put the emphasis on applicability in today’s world in our culture, devoid of religious connotations. My work is based on values that are the right of every being at birth - health, quality of life, good will and the potential to be happy.\nPayment Methods\nYou can also renew the monthly membership fee by making a bank payment to the account of the Association.\nRECEIVER: Biševo Association, Porat 13, 21485 Komiža\nAccount number (IBAN): HR2623400091111064242\nBIC (SWIFT CODE): PBZGHR2X\nModel and reference to approval number: In the "model" box, enter 00. In the "call to recipient number" box, enter the date of payment in the form of DAY-MONTH (example 0105).\nDescription of payment: Monthly membership fee (NAME AND SURNAME)\nAmount: You enter the amount of the membership fee in euros.\nBank: Privredna banka Zagreb d.d.\n2. Paypal\nHvala vam i vidimo se online, Tena :)\nPrenatal Yoga Sign Up Form\nPlease leave this field empty.Please leave this field empty.Please leave this field empty.Please leave this field empty.\nYour personal data is used for enrollment purposes and remains private. After filling out the registration form, send us the confirmation of payment to [email protected] mail. The confirmation of payment activates your monthly membership fee. We look forward to practice yoga with you and your baby. :)\nWhat is your experience with yoga so far?\nI confirm that I agree to participate in prenatal yoga program at my own risk. I accept the condition that I will not sue the program teachers, their associates and members for any injuries or unwanted condition regardless of the cause. I agree to the collection of my personal data for the purpose of running the program. You accept the objectives and operation of the program and declare that you will act in accordance with them. The presenters have the right to ask you to leave the group if you disturb the work or are unable to participate.\nGENERAL INSTRUCTIONS FOR EXERCISE DURING PREGNANCY It is necessary to have approval from a gynecologist that the pregnancy is normal and that there are no obstacles to exercise. Listen to your body and your limits. Do not overheat. Make sure you never run out of breath. Avoid positions in which the abdomen is squashed or squeezed. Don\'t jump. Do not do balance poses if you are unstable. You are aware that you exercise at your own risk.',
        "Information\nWelcome\nAll offers are due to availability. Once we have received your wine order our confirmation validates this transaction. Within 24 hours you will receive a confirmation of your order.\nShould a desired vintage be sold out\n- we will then send the following vintage-wines that cost no more than EUR 10.- (unless you oppose)\n- we will contact you - should the wine happen to cost more than EUR 10.- per bottle\nThere is a minimum order of six bottles per wine selection; each bottle contains 0,75 l.\nWe will deliver after payment has arrived.\nCosts for transport:\nwithin GERMANY - FREE\nEUROPEAN COUNTRIES - EU 6.00 (per parcel with up to 12 bottles) for tranport to the following countries.\nBelgium\nCzech Republic\nDenmark\nFrance\nGreat Britain\nGreece\nHungary\nIreland\nItaly\nLuxembourg\nNetherlands\nPoland\nPortugal\nSpain\nSlovakia\nSlovenia\nSweden\nRomania: EUR 8.00 per parcel (with max. 12 bottles)\nSwitzerland: EUR 20.00 per parcel (with max. 12 bottles)\nOTHER COUNTRIES. we will send you an offer\nWe insure all our products - but please be sure to check the quality of the products upon receival and in the presence of the delivery person. In case of any damage do not accept the order.\nPlease contact us right away\ntel: ++49-4171 692 716 / email: info@inter-wein.de\nIf you are not completely satisfied with a particular wine you have three weeks time to return the unopended bottles if the order does not contain more than six bottles of that wine - you will receive a refund.\nWe will not be held accountable for „corked“ wine; deposit is not considered to be damaged quality and may not be exchanged.\nPossible forms of payment\n* money transfer\nbankaccount:\nthe amount is transferable to the account number given below\ninter-wein.de gmbh\npostbank dortmund: banknumber 440 100 46\naccount no: 112 674 469\nIBAN DE34 4401 0046 0112 6744 69\nBIC PBNKDEFF\npaypal: martin@inter-wein.de\n* pay upon delivery (there is an extra charge of EUR 2,00 in germany and EUR 12,50 within EU)",
        "Model has a standard non-tobacco livery. Extra tobacco decals are included with the model!\nWe also offer this model with the missing Marlboro decals already appied (click on the picture below to go to the product page)\nShare\nLink\nContact Info\nRace Passion Store Belgium\nT: +32 483 40 32 42\ninfo@racepassionstore.com\nIBAN: BE80 0017 2804 3377\nBIC: GEBABEBB\nVAT: BE0781.530.582\nDisclaimer\n* Please note that we o\xadnly use the EURO (European currency). All prices are quoted and invoiced in EUROs. Prices in other currencies are indicated for your information o\xadnly, and are subject to slight adjustments due to the exchange rate variation. Prices in EURO including VAT. All prices plus dispatch costs.",
    ]

    analyzer = READIAnalyzer(READIAnalyzer.DetectionType.PII)

    analyzer.entity_extractors

    for example in examples:
        entities = analyzer.detect(example)
        print(entities)

    assert False, "for debugging purposes"


@pytest.mark.skip("Only for local test")
def test_more():
    data_1 = "Supplier\nSKU\nSize Chart\nIf you’re looking for one-off custom printed tees, singlets and hoodies or want to create your very own design, head to thetshirtco.com.au. With our in-house state of the art Kornit digital printers, we offer the latest in textile decoration. For the best price on smaller quantities of 1 to 19 units, visit thetshirtco.com.au."
    analyzer = READIAnalyzer(READIAnalyzer.DetectionType.PII)

    analyzer.detect(data_1)

    data_2 = "stacey_balkun\nStacey Balkun is the author of Sweetbitter & co-editor of Fiolet & Wing: An Anthology of Domestic Fabulist Poetry. Winner of the 2019 New South Writing Contest as well as Terrain.org’s 10th Annual Contest, her work has appeared in Best New Poets 2018, Mississippi Review, The Rumpus, Pleiades, & several other anthologies & journals. Stacey holds an MFA from Fresno State and a BA from Rutgers University, and currently teaches creative writing online at The Poetry Barn & The Loft. Visit her online at www.staceybalkun.com."

    analyzer.detect(data_2)

    assert False


@pytest.mark.skip("Only for local test")
def test_specifics():
    analyzer = READIAnalyzer(READIAnalyzer.DetectionType.PII)

    # assert False, analyzer.detect("Stacey Balkun")
    assert False, analyzer.detect("www.staceybalkun.com.")
